
# Author: Ruben Gutierrez
# My Website: http://ruben-g.com


title: News-letter
email: 
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

sass:
  sass_dir: _sass
  style: compressed

